Regression-Games/RGUnityBots

- Runtime/Scripts/RGCertificateHolder.cs
- Runtime/Scripts/RGServiceManager.cs
- Fixes a bug where we were logging off the main thread and causing certs to fail to load sometimes
> [REG-1183] Cleanup RGCertOnlyPublicKey to not log off main thread

- Runtime/Prefabs/RGOverlayCanvas.prefab
Changes:
* Canvas scaler on overlay now has default setting of "Scale with screen size" instead of "Constant Pixels", which can remove the need for devs to adjust it when first adding it to scene
> [REG-1209] - Set canvas to relative screen size, not constant size

- Runtime/Scripts/RGOverlayMenu.cs
- Runtime/Scripts/RGServiceManager.cs
Looking at the comments here:
https://linear.app/regression-games/issue/REG-1205/log-error-for-instant-bot-queueing
It's possible no further information is available, except to determine which service has failed. Is the value added by the warning messages worth the extra inspector logs?
> [REG-1205] Log error for instant bot queueing

- .gitignore
- Runtime/Scripts/Attributes/RGStateAttribute.cs
- Runtime/Scripts/RGBotLocalRuntime/RG.cs
- Runtime/Scripts/RGBotLocalRuntime/SampleBot/RGSampleBot.cs
- Runtime/Scripts/RGBotLocalRuntime/Template/BotEntryPoint.cs.template
- Runtime/Scripts/RGBotServerListener.cs
- Runtime/Scripts/RGServiceManager.cs
- Runtime/Scripts/StateActionTypes/RGStateEntity.cs
- Runtime/Scripts/Types/BotInformation.cs
- Runtime/Scripts/Types/RGBotUnityState.cs
- Runtime/Scripts/Types/RGClientConnection_Remote.cs
- Runtime/Scripts/Types/RGClientHandshake.cs
- Runtime/Scripts/Types/RGServerHandshake.cs
- Changes characterConfig from a plain string to a `Dictionary<string, object>` to make writing local bots somewhat sane
- Handles/Compensates for existing remote bots sending poorly formatted JSON strings for backward compatibility
- Exposes `SceneName` as a field on `RG` accessor object
- Adds Filter Function support to `FindNearestEntity` for parity with javascript version
- Adds a `object GetField(string fieldName)` method onto `RGStateEntity` to simplify coding patterns for getting fields from state entities
See also https://github.com/Regression-Games/RegressionDocs/pull/36
See also https://github.com/Regression-Games/RGBossRoom/pull/34
> [REG-1308] Update characterConfig to Map and RG api enhancements

- Editor/Scripts/CodeGenerators/GenerateRGActionClasses.cs
- Editor/Scripts/CodeGenerators/GenerateRGActionMapClass.cs
- Editor/Scripts/CodeGenerators/GenerateRGSerializationClass.cs
- Editor/Scripts/CodeGenerators/GenerateRGStateClasses.cs
- Editor/Scripts/CodeGenerators/RGActionCodeGenerator.cs
- Moves generated scripts from `Assets/RGScripts` to `Assets/RegressionGames/Runtime/GeneratedScripts`
- Handles removing the old folder to avoid classname conflicts
- Fixes an issue where generating scripts more than once would fail to generate the zip
- Updated path for the temp zip folder to avoid confusion with the `RegressionGames` folder in `Assets`
See also https://github.com/Regression-Games/RegressionDocs/pull/37
> [REG-1304] Move generated scripts under RegressionGames asset path

- Editor/Scripts/CodeGenerators/GenerateRGActionClasses.cs
- Editor/Scripts/CodeGenerators/GenerateRGActionMapClass.cs
- Editor/Scripts/CodeGenerators/RGActionCodeGenerator.cs
- Editor/Scripts/RGActionInfo.cs
- Runtime/Scripts/RGBotConfigs/RGClickButtonAction.cs
- Generates new classes extending RGActionRequest for each action to provide typed action requests when coding in C#
- Fixes the issue with namespaces for actions in the action map and in the generated action class
- Sample
```csharp
public class RGActionRequest_PerformAttack : RGActionRequest
{
public RGActionRequest_PerformAttack(bool isEnabled, string actionName, int attackNumber, float damageAmount)
{
action = "PerformAttack";
Input = new ()
{{"isEnabled", isEnabled}, {"actionName", actionName}, {"attackNumber", attackNumber}, {"damageAmount", damageAmount}, };
}
}
```
See also https://github.com/Regression-Games/RegressionDocs/pull/38
> [REG-1302] Adds typed `RGActionRequest`s to generated code

- Editor/Scripts/RGBotReplayWindow.cs
- Editor/Scripts/RGTickInfoActionManager.cs
- Runtime/Prefabs/RGOverlayCanvas.prefab
- Runtime/Scripts/RGBotConfigs/RGButtonState.cs
- Runtime/Scripts/RGBotConfigs/RGEntity.cs
- Runtime/Scripts/RGBotConfigs/RGState.cs
- Runtime/Scripts/RGBotLocalRuntime/RG.cs
- Runtime/Scripts/RGBotLocalRuntime/SampleBot/RGSampleBot.cs
- Runtime/Scripts/RGBotLocalRuntime/Template/BotEntryPoint.cs.template
- Runtime/Scripts/StateActionTypes/RGStateEntity.cs
- SampleBots/BossRoom/AbilityBot_0/BotEntryPoint.cs
- SampleBots/BossRoom/MenuAbilityBot_1/BotEntryPoint.cs
- RGEntities now have mandatory, non-nullable `positions` and `rotations`. They will always be synced
- Added a check to ensure that skills aren't used on UI components. They are found the same as enemies or allies in BossRoom, but lack a `position`
To test this I created a remote bot that logs the position of all player characters in a game of BossRoom. I tested the game using the remote bot and a local bot. In the remote bot logs we can see the Vector3 position of the player characters update:
https://www.loom.com/share/7c6e22fbc0b94af6b46965b572b0a4be
```
const state = rg.getState().gameState;
const res = Object.keys(state)
.filter(key => state[key].isPlayer)
.map(key => `${state[key].position.x}, ${state[key].position.y}, ${state[key].position.z}`);
```
> [REG-1303] non-nullable, always synced RGEntity position and rotation

- Runtime/Scripts/RGBotSpawnManager.cs
- Runtime/Scripts/Types/RGClientConnection_Remote.cs
Not Perfect, but should reconnect remote bots automatically in most scenarios.
- Thread safety / concurrency fixes around network connection management
- Resolves an issue where sometimes we wouldn't re-connect as necessary due to a concurrency issue setting/reading a variable
- Changes to better detect most socket state failures before read and write
- Added socket read/write timeouts to make failures detect properly
- Fixed socket read code to address issues handling transient errors / empty buffer during read attempts
> [REG-1273] Harden network connectivity and re-connects

- Runtime/Scripts/RGBotServerListener.cs
* When a GameObject has multiple scripts extending RGState, squash them into one object for tickinfo
* Inherit `isPlayer` and `isRuntimeObject` from GameObject's `RGEntity` instead of letting state scripts override these values
Tested this against my platformer project + BossRoom local and remote bots
> [REG-1336] allow multiple state scripts per GameObject

- Editor/Scripts/CodeGenerators/GenerateRGStateClasses.cs
- Editor/Scripts/CodeGenerators/RGActionCodeGenerator.cs
- Editor/Scripts/RGStatesInfo.cs
Fixes compile errors after `Regression Games -> Generate Scripts` 
**To Test**
Add `[RGAction]` and `[RGState]` attributes to a class with a custom namespace
```
using UnityEngine;
using RegressionGames;
namespace TestNamespace
{
public class Test : MonoBehaviour
{
[RGState]
public int testState = 5;
[RGAction]
public void TestAction()
{
Debug.Log("Test Action");
}
private void Start(){}
}
}
```
Generate scripts. `Regression Games->Generate Scripts`. Generated files should include `using TestNamespace;`
> [REG-1333] - Add namespace to generated state files

- Editor/Scripts/Startup/RegressionPackagePopup.cs
**Changes**
* Added an automatic 'Import Sample' button to the welcome screen
* Automatically opens Playground scene after import
* Enables/Disables import button if the project is setup with URP
_Enabled when using URP_
_Disabled when not using URP_
> [REG-1367] Add 'Third Person Sample' to welcome screen

- Runtime/Scripts/BehaviorTree.meta
- Runtime/Scripts/BehaviorTree/ActionNode.cs
- Runtime/Scripts/BehaviorTree/ActionNode.cs.meta
- Runtime/Scripts/BehaviorTree/BehaviorTreeNode.cs
- Runtime/Scripts/BehaviorTree/BehaviorTreeNode.cs.meta
- Runtime/Scripts/BehaviorTree/ConditionNode.cs
- Runtime/Scripts/BehaviorTree/ConditionNode.cs.meta
- Runtime/Scripts/BehaviorTree/Decorators.cs
- Runtime/Scripts/BehaviorTree/Decorators.cs.meta
- Runtime/Scripts/BehaviorTree/NodeStatus.cs
- Runtime/Scripts/BehaviorTree/NodeStatus.cs.meta
- Runtime/Scripts/BehaviorTree/RGBehaviorTreeBot.cs
- Runtime/Scripts/BehaviorTree/RGBehaviorTreeBot.cs.meta
- Runtime/Scripts/BehaviorTree/RootNode.cs
- Runtime/Scripts/BehaviorTree/RootNode.cs.meta
- Runtime/Scripts/BehaviorTree/SelectorNode.cs
- Runtime/Scripts/BehaviorTree/SelectorNode.cs.meta
- Runtime/Scripts/BehaviorTree/SequenceNode.cs
- Runtime/Scripts/BehaviorTree/SequenceNode.cs.meta
- Runtime/Scripts/RGBotLocalRuntime/RG.cs
- Runtime/Scripts/RGBotLocalRuntime/RGUserBot.cs
This adds a new namespace: `RegressionGames.BehaviorTree`. Inside this namespace are types to support Behavior Tree-based bots in the Unity SDK. This includes bots generated by Agent Builder, but also allows users to integrate behavior trees into their own bots if they'd like to use a hybrid approach.
A Behavior Tree-based bot inherits from `RGBehaviorTreeBot` **instead** of `RGUserBot`. Then, instead of overriding `ProcessTick`, they override `BuildBehaviorTree` to construct their behavior tree and return the root node.
As part of this change, I've made `RGUserBot.Init` `internal`. I don't think there's reason for a user script to call it, so it probably shouldn't be public, but I can revert that if we know user scripts need to call it. It's also `virtual` now, which allows …
> [REG-1376] Behavior Tree Bots and supporting components

- Editor/Scripts/Startup/RegressionPackagePopup.cs
Changes:
* Changed menu item from "Setup" to "Getting started"
* Refactored to use 'EditorPrefs' over 'PlayerPrefs' for better code practice for editor windows
* Added a "Continue as Guest" button to skip log in and go directly to Quickstart page
* Added a "Always show on startup" checkbox to determine if welcome screen should appear when Unity starts up
> [REG-1362] Welcome Screen Improvements

- Runtime/Scripts/RGBotLocalRuntime/RG.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotRunner.cs
I thought I made `RG.SetCharacterConfigFromJson` a `public` method but I guess not 😩 . Anyway, it needs to be public so that user bots can call it. Our generated Agent Builder code includes a call to `SetCharacterConfigFromJson`:
```csharp
public class BotEntryPoint : RGBehaviorTreeBot
{
protected override bool GetIsSpawnable() => true;
protected override RGBotLifecycle GetBotLifecycle() => RGBotLifecycle.MANAGED;
private const string CharacterConfig = @"{}";
public override void ConfigureBot(RG rgObject)
{
rgObject.SetCharacterConfigFromJson(CharacterConfig);
}
protected override RootNode BuildBehaviorTree()
{
var rootNode = new RootNode();
rootNode.AddChild(new SequenceNode());
return rootNode;
}
}
```
Also, Rider went ahead and cleaned up some trailing spaces 🤣 . If you turn "Ignore …
> [REG-1397] Make SetCharacterConfigFromJson public so user bots can call it

- Runtime/Scripts/RGBotLocalRuntime/RGBotRuntimeManager.cs
- Updates expected bot namespace pattern to be independent of directory path when possible
- This isn't perfectly clean, but handles both synced and locally created but unsynced bot cases as best as currently possible.
- We may have to consider mucking with the user's bot code namespace values when syncing bots as their ids change to avoid them having to do weird work.  I don't like this suggestion, but haven't come up with another way to ensure their namespace is correct 100% of the time.  Basically we'd need to lookup the namespace for their `BotEntryPoint.cs`.  If that namespace didn't comply, then we'd need to change it, as well as any other files that had that exact same namespace.  We can't change ALL files as they may have a complex bot with multiple namespaces.
- See also …
> [REG-1401] Update bot namespace loading patterns

- Editor/Scripts/CodeGenerators/RGCodeGenerator.cs
- Handles looking up objectTypes from all scenes, not just the current active ones
- Includes logic for restoring their editor scenes back to the same open/active scenes they started with, including keeping scenes original loaded/unloaded states.
- Includes prompting to warn about this as well as handle unsaved scene changes.
> [REG-1373] Populate state and action json from all scenes

- Runtime/Scripts/BehaviorTree/Decorators.cs
Found this while working on some remote bot syncing code. We require that a decorator node has a child in it's constructor. However, that's not required by the Agent Builder design surface. It also makes sense to have decorators without children. The `AlwaysSucceed` and `AlwaysFail` decorators can do their job regardless of whether or not they have children.
Matching RGService PR: https://github.com/Regression-Games/RegressionGames/pull/431
> [REG-1419] Allow decorator nodes to have no children

- Editor/Scripts/BotManagement/RGBotSynchronizer.cs
- Editor/Scripts/CodeGenerators/CodeGeneratorUtils.cs
- Editor/Scripts/CodeGenerators/GenerateRGActionClasses.cs
- Editor/Scripts/CodeGenerators/GenerateRGActionMapClass.cs
- Editor/Scripts/CodeGenerators/GenerateRGSerializationClass.cs
- Editor/Scripts/CodeGenerators/GenerateRGStateClasses.cs
- Editor/Scripts/CodeGenerators/RGCodeGenerator.cs
- Editor/Scripts/Startup/RegressionPackagePopup.cs
- Runtime/Scripts/BehaviorTree/Decorators.cs
- Runtime/Scripts/BehaviorTree/SequenceNode.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotAssetsManager.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotRuntimeManager.cs
- Runtime/Scripts/RGRuntimeProperties.cs
- Runtime/Scripts/RGRuntimeProperties.cs.meta
- Runtime/Scripts/RGSettings.cs
- Runtime/Scripts/RGUtils.cs
- Add `#if UNITY_EDITOR` to files as needed to properly exclude Editor libraries from production builds
- Unbreaks the ability for users to actually build their projects
- We still can't run our bots in their production builds, but we'll fix that as a follow up task as it gets more complicated
> [REG-1423] Fix issues where editor libraries were preventing project builds

- Editor/Scripts/CodeGenerators/GenerateRGActionClasses.cs
- Runtime/Scripts/DataCollection/RGDataCollection.cs
- Runtime/Scripts/RGServiceManager.cs
- Runtime/Scripts/StateActionTypes/RGValidationResult.cs
Fixes an issue with enum serialization for validations. Before they would be sent as integers, but the frontend expected strings. This has been updated to use strings now.
Also adds a quick fix for a threading issue I saw.
UPDATE: Also adds a quick fix for action classes where the namespace would be incorrect.
---
> [REG-1433] Fix issue with enum serialization

- Runtime/Scripts/RGBotLocalRuntime/RGBotAssetsManager.cs
In Windows, there was an error (described in the linear ticket for this task). I _believe_ this is because in windows, there is no trailing slash included in the path, so there is an out of bounds error when trimming the path because of a -1 index.
However, I have no access to a Windows computer rn, so I cannot confirm that this works. However, I did the next best thing and had GPT review this error, and it came to the same conclusion and reasoning, so I'm pretty confident this should work... https://chat.openai.com/share/1b7c364c-9a91-4ac1-ba2e-f14e1560d2ef
---
Every reviewer and the owner of the PR should consider these points in their request (feel …
> Fix for unneeded path fixing in Windows

- Editor/Scripts/BotManagement/RGBotSynchronizer.cs
Oof, missed a case when testing #96. If there's no bot on the server, we create a record. But then, when we go to fetch the server-side code details to check if we should upload, we find there is no code and assume that means we shouldn't upload. This was a misunderstanding on my part, assuming that meant there would be nothing to sync, but that's not the case 🤦🏻‍♀️ .
The fix here is simple: if there's no code on the server, we must upload!
---
> [REG-1415] Upload bot when there's no bot code

- Editor/Scripts/BotManagement/RGBotSynchronizer.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotAssetsManager.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotRuntimeManager.cs
- Fixes namespace generation bug introduced in (https://github.com/Regression-Games/RGUnityBots/pull/100)
- Fixes asset pathing for both Windows and Mac for bot creation and loading
> [REG-1461] Fix bot creation and loading on Windows

- Runtime/Scripts/RGBotLocalRuntime/RG.cs
Exposes the tick number as a property that can be accessed from the rgObject argument in local bots. Useful for scenarios where you want your bots to wait for a certain amount of time.
---
> [REG-1474] Expose the tick number to local bots

- Runtime/Scripts/DataCollection/RGDataCollection.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotRuntimeManager.cs
- Runtime/Scripts/RGServiceManager.cs
- Asynchronously writes replay data, validations, screenshots, etc to disk on each tick to avoid filling up memory with the data
- Tracks validation summary in a running fashion for each client in memory
- Uploads the data from the files directly without fully reading into memory first
---
> [REG-1425] Handle replay data / screenshot / validation disk buffering

- Editor/Scripts/Startup/RegressionPackagePopup.cs
- Runtime/Scripts/DataCollection/RGDataCollection.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotRunner.cs
- Runtime/Scripts/RGBotLocalRuntime/SampleBot/RGSampleBot.cs
- Runtime/Scripts/RGBotLocalRuntime/Template/BotEntryPoint.cs.template
- Runtime/Scripts/RGBotServerListener.cs
- Runtime/Scripts/RGDebug.cs
**Changes**
Cases where we had:
```
catch (Exception e) {
RGDebug.LogError($"Some Error Message - {e});
}
```
have been updated to:
```
catch (Exception e) {
RGDebug.LogException(e, "Some Error Message");
}
```
and `RGDebug.LogException` has been updated to include an option string message that will log as a warning
This maintains clickable callbacks
---
> [RG-1489] Use 'RGDebug.LogException' as required

- Runtime/Scripts/DataCollection/LogDataPoint.cs
- Runtime/Scripts/DataCollection/LogDataPoint.cs.meta
- Runtime/Scripts/DataCollection/RGDataCollection.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotRunner.cs
- Runtime/Scripts/RGServiceManager.cs
This adds support to the Unity SDK to collect logs during bot execution. There are a few limitations in this first version, which lead to some open questions.
Log collection works as follows:
1. Prior to any bot starting, the `RGDataCollection` constructor hooks in to `Application.logMessageReceivedThreaded`, which is called when a log message is emitted **on any thread**.
2. When a bot starts, `RGDataCollection.RegisterBot` is called. This adds a `ConcurrentQueue<LogDataPoint>` to the `ConcurrentDictionary<long, ConcurrentQueue<LogDataPoint>>` tracking which bots are running and listening to logs. This starts collection of logs for this bot.
3. Each tick of the bot, we perform an atomic swap of the active log message queue with a new empty queue. This allows us to flush that set of …
> [REG-1473] Collect logs during bot execution and upload

- Runtime/Scripts/RGBotConfigs/RGEntity.cs
- Runtime/Scripts/RGBotConfigs/RGState.cs
- Defaults the `RGEntity` objectType to the name of the GameObject if not specified.
---
> [REG-1479] Default objectType to the gameObject name less qualifiers

- Runtime/Prefabs/RGOverlayCanvas.prefab
- Changes default tick rate from 50 to 5 on the Overlay prefab
---
> [REG-1498] Change default tick rate from 50 to 5

- Editor/Scripts/CodeGenerators/GenerateRGActionClasses.cs
- Editor/Scripts/CodeGenerators/GenerateRGActionMapClass.cs
- Editor/Scripts/CodeGenerators/GenerateRGSerializationClass.cs
- Editor/Scripts/CodeGenerators/GenerateRGStateClasses.cs
- Editor/Scripts/CodeGenerators/RGCodeGenerator.cs
- Limits AssetDatabase.Refresh calls to 1 instead of 1 per file generated
- Writes states/actions files async to one another.
---
> [REG-1522] Shorten code generation time

- src/gg.regression.unity.bots/Editor/Scripts/CodeGenerators/RGCodeGenerator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/Attributes/RGStateAttribute.cs
More details in the linear ticket, but I can't quite see why we support Delegates for the `RGState` attribute, so I'm opening this PR to remove it. Happy to adjust if I'm missing something here.
We allow you to apply `RGState` to a delegate type:
```csharp
public class MyBehavior: MonoBehavior
{
[RGState]
public delegate string Foo();
}
```
What I don't understand is what we expect that to do. Delegates are types, and have no value at runtime. They are named function signatures. The following C#:
```csharp
public delegate bool Predicate<T>(T value)
```
Is equivalent to this Kotlin:
```kotlin
typealias Predicate<T> = (T) -> Boolean
```
In fact, the code we generate ends up trying to call `myBehavior.Foo()`, where `myBehavior` is an instance of `MyBehavior`. That isn't valid C# since `Foo` …
> [REG-1524] Don't allow RGState on delegates anymore

- src/gg.regression.unity.bots/Editor/Scripts/RGSettingsUIRegistrar.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGUserSettings.cs
**Changes**
Fixes bug where editing the email or password in `Project Settings -> Regression Games` would not save changes, causing the values to go back when clicked away
---
> Fix user settings updating durring settings windows input updates

- src/gg.regression.unity.bots/Editor/Scripts/RGEditorUtils.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGBotLocalRuntime/RGBotRuntimeManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
Patches our C# SDK code so that customers including our SDK can still build their game for production.
REG-1488 and REG-1619 broke this
This is a stopgap PR until REG-1424 is prioritized and fixed.
---
> [REG-1637] Patch C# SDK so that production builds in Unity are possible

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Fixes a crash in production builds of game using our SDK where a NativeArray operation would often crash the game
---
> [REG-1684] Fix NativeArray screenshot capture crash

- src/gg.regression.unity.bots/Runtime/Scripts/RGSettings.cs
Fixes an issue found during UAT: When the resources folder doesn't exist, we need to create it before making the settings asset.
---
> [REG-1686] Fix resource directory creation issue, fix sample

- src/gg.regression.unity.bots/Editor/Scripts/RGSettingsUIRegistrar.cs
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlayCanvasV2.prefab
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/KeyboardInputActionObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataContainer.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
Sends text events specifically for GameFace inputs to receive characters and produce `onChange` events. This requires us to take `shift` into consideration so that we know which character to send based on whether `shift` is held at the same time as another key.
https://www.loom.com/share/1084658e11c5412e8d70b6d1fc9abd94
---
> [REG-1626] Enable replay interaction with Coherent GameFace components

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/InGameObjectFinder.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/RecordingAndReplayContainerTypes.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- Handles adjusting the click location of clicks on world space objects to handle slight positional differences of the player/view from run to run
- This is more of a fix than new code... We were wrongly excluding duplicate path named world space objects from click adjustment consideration during replay and were using the render bounds instead of colliders to check for click hits
- Fixes an issue where non-visible world space objects were sometimes being included incorrectly in the recorded state
- Fixes an issue where we weren't including the screenSpaceZOffset in the json
- **(This will change the Json by adding a new field to each object)**
---
Every …
> [REG-1679] Handle world space object click position adjustments

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/InGameObjectFinder.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseInputActionObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/RecordingAndReplayContainerTypes.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataContainer.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayToolbarManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/StateRecorderUtils.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/StateRecorderUtils.cs.meta
- DOES NOT address JSON serialization performance
- Heavily micro-optimizes object constructions, pooling, reuse, loop iterations, and other code to limit GC allocs and improve performance.. kinda turns the code into a thread safety nightmare.. but luckily.. unity requires all this to run on the main thread.. so we can cheat a lot to get better performance and re-use structures
- Also handles replay performance optimization both for getting current state and for analyzing key frames and processing mouse inputs
- Fixes issues with dynamic resolution scaling on replay related to mouse click and release points <- this was actually annoying to fix :/ 
- Reduces flicker of keyframe wait text by delaying presentation of said text for a few seconds worth of frames if not matched
- Updates file …
> [REG-1680] Optimize performance of state for current frame

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/InGameObjectFinder.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseInputActionObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/RecordingAndReplayContainerTypes.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Removes duplication of behaviour/collider/rigidbody states on parent objects vs child objects
- Hand compared old and new states to ensure that things are showing up only once and that everything is still showing up for BossRoom
- This change improved the performance of `ToJsonString` which runs only on KeyFrame ticks; the improvement is due to the reduction in behaviour json being written to the state (behaviours are the most expensive thing to convert to json)
- new - 11.78ms , old - 16.31ms 
- This change also reduced the GC allocs for a KeyFrame tick due to the reduction in state being recorded 
- Adapts prior state code paths to use a dictionary instead of a list to further improve performance with high object counts in a tick
- This primarily improves the performance of …
> [REG-1709] Remove behaviour state duplication + improve performance

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/StringJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/RecordingAndReplayContainerTypes.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataContainer.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayToolbarManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Add sessionId and referenceSessionId fields to each tick so that backend data can be queried based on related recordings and replays
- Also adds a method to the StringJsonConverter to make it more consistent with other types
Recording
Replay Recording
---
> [REG-1710] Add sessionId correlators to recording data

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/InGameObjectFinder.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/AnimatorJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/ImageJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/MeshFilterJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/NavMeshAgentJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/ParticleSystemJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/RawImageJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/SkinnedMeshRendererJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/StringJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/TextJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/TextMeshProJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/TextMeshProUGUIJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonUtils.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/KeyboardInputActionObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseInputActionObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/RecordingAndReplayContainerTypes.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataContainer.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Now writes the 'true' path to `path` and the 'normalized' path (what we had before without uniqueness numbers) to `normalizedPath`...
**- This is NOT strictly backwards compatible, but in a non-breaking way... The data in `path` is similar, but not the same from the client UI perspective**
- This negatively impacts performance as we are now computing and writing out 2 similar strings for every object... if we determine that we don't need this on the Client UI, I'd LOVE to remove `normalizedPath` as I can compute it on replay load easily for handling mouse clicks ... if we remove it though.. similar game objects cloned from prefabs will no longer have the same `normalizedPath` to work from in the client UI validations
- Uses the `normalizedPath` for game object and `path` for UI objects …
> [REG-1708] Use real paths for UI object clicks

- src/gg.regression.unity.bots/Runtime/Scripts/RGSettings.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Enables state recording feature by default
- Makes another attempt at hiding the coroutine error on destroy
---
> [REG-1737] Enable State Recording Feature By Default

- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlayCanvasV2.prefab
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ProfilerObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ProfilerObserver.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/RecordingAndReplayContainerTypes.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
This is the bare minimum implementation of capturing CPU utilization (in terms of time spent on the main thread), and memory utilization (amount of bytes the operating system reports in use by the application). 
This uses the [ProfilerRecorder](https://docs.unity3d.com/ScriptReference/Unity.Profiling.ProfilerRecorder.html) API available in recent versions of Unity (2021.3+). It begins profiling when the recording starts, and stops profiling when the recording ends. 
The memory usage is obtained via reading the profiler counter for *System Used Memory* (which is defined by the Unity docs as the memory usage reported by the OS: https://docs.unity3d.com/Manual/ProfilerMemory.html). 
CPU time is obtained in terms of nanoseconds spent on the main thread. The "Main Thread" stat appears to be …
> [REG-1729] Capture memory and CPU utilization

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataContainer.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- Fixes a bug where we showed the hash id instead of the pathname in keyframe errors
---
> [REG-1762] Fix error message showing paths not hashes

- src/gg.regression.unity.bots/Editor/Scripts/RGLegacyInputUtility/RGLegacyInputInstrumentation.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGLegacyInputUtility/RGLegacyInputWrapper.cs
This PR introduces support for simulating inputs for the legacy input mouse event handlers found in MonoBehaviour methods:
`OnMouseDown()`
`OnMouseDrag()`
`OnMouseEnter()`
`OnMouseExit()`
`OnMouseOver()`
`OnMouseUp()`
`OnMouseUpAsButton()`
This emulates the same logic used by the Unity runtime for invoking these methods. The Unity engine handles these in the same module as the legacy input handling APIs, so I consider them to be part of the legacy input as well and implement their handling in the `RGLegacyInputWrapper` event loop.
Also, this PR includes a small bugfix/optimization for the legacy input instrumentation to compare assemblies by name instead of path (this was causing unnecessary assemblies to be processed when creating standalone builds, since the assembly output path changes …
> [REG-1763] Support mouse inputs handled via MonoBehaviour methods + instrumentation bugfix

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/InGameObjectFinder.cs
- Fixes a bug in Bot Segments PR for world space UI elements that don't have an event camera
---
> [REG-1775] Fix world space camera

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/InGameObjectFinder.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/StringJsonConverter.cs
- Oops, apparently when you're only testing bot segments, you miss field value regressions in state date.  Ty @addisonbgross for catching that bounds weren't being updated from tick to tick
---
> [REG-1804] Bounds weren't updated for each tick

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/RandomMouseObjectActionData.cs
- one of the using statements in the bot segments pr incorrectly point to plastic.newtonsoft instead of just newtonsoft
---
> Fix an issue with using for newtonsoft

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/InGameObjectFinder.cs
- Fixes a bug where the new fill in the tree objects weren't cleared between runs
---
> [REG-1808] Fix - Clear tree view filler objects on next replay

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/AndKeyFrameCriteriaEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/RandomMouseObjectActionDataJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/KeyFrameEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotAction.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/IBotActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/InputPlaybackActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/RandomMouseObjectActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/RandomMousePixelActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/NormalizedPathCriteriaEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/OrKeyFrameCriteriaEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/InGameObjectFinder.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayBotSegmentsContainer.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- Renders excluded areas
- Adds option to allow or disallow mouse movement with buttons held down
- Makes bot segment log message formats more consistent for easier filtering in unity
- Fixes a bug in state capture where a destroyed transform wasn't being handled
---
> [REG-1810] Render excluded click areas for mouse bot segments

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/KeyFrameEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/UIPixelHashKeyFrameCriteriaData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/UIPixelHashKeyFrameCriteriaData.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/GameFacePixelHashObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Updates pixelhash code to work with bot segments
- Adds botsegment keyframecriteria type
---
> [REG-1783] Pixel Hash Bot segment type

- src/gg.regression.unity.bots/Editor/Scripts/RGLegacyInputUtility/RGLegacyInputInstrumentation.cs
This PR fixes an error message that occurs when first loading the RG SDK package. The error is brief and goes away after Unity restarts after installing the input system package, so this is not an urgent issue.
---
> [REG-1820] Fix brief error message from input instrumentation code when first loading the RG package

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/PerFrameStatisticsData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/PerFrameStatisticsData.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/PerformanceMetricData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ProfilerObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
This PR introduces a `perFrameStatistics` field to the performance field, which collects profiler and engine stats for every frame of the tick. This is a revised version of an earlier PR (see [here](https://github.com/Regression-Games/RGUnityBots/pull/210) for background).
This implements the format that was suggested in the prior PR. The data size is about 350 to 380 bytes per frame. Note that the first tick will have `null` values for the profiler data.
I've tested this code both in the in-editor and standalone builds of Boss Room.
Examples:
[1.json](https://github.com/user-attachments/files/16073618/1.json)
[7.json](https://github.com/user-attachments/files/16073626/7.json)
---
Find the pull request instructions [here](https://www.notion.so/regressiongg/Pull-Request-Process-0d57a7eb582a …
> [REG-1818] Record profiler statistics per frame

- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlayCanvasV2.prefab
This PR fixes an issue that prevents the RG bot overlay dropdowns from being usable. This reduces the sort order of the RG overlay canvas from 32767 (the maximum) to 29999 to accommodate TextMeshPro, which uses a hard-coded sort order of 30000 for its dropdown canvas.
Before:
After:
---
> [REG-1819] Fix bot overlay dropdowns

- src/gg.regression.unity.bots/Editor/Scripts/RGLegacyInputUtility/RGLegacyInputInstrumentation.cs
For various reasons, the initial attempt at instrumenting the legacy input API usage in the assemblies could fail (e.g. file in use by another job). 
This PR introduces graceful handling of these errors. If the initial instrumentation fails, a couple more attempts are scheduled with exponential backoff. Ultimately if all these attempts fail, the user is warned that the SDK's legacy input support may not work and the user should consider rebuilding the game code.
---
> [REG-1848] Gracefully handle IO errors during legacy input instrumentation

- src/gg.regression.unity.bots/Runtime/Scripts/ActionManager/Actions/MouseHoverObjectAction.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/BehaviourActionDataJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/BehaviourActionDataJsonConverter.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BehaviourActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BehaviourActionData.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotAction.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotActionType.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/IBotActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/InputPlaybackActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/RandomMouseObjectActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/RandomMousePixelActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/SdkApiVersion.cs
- Adds a StopAction method to BotSegment action data so that actions like monobehaviours or random actions can be stopped.
- Adds support for monobehaviour actions
---
> [REG-1862] Stoppable Bot Segment Actions + Monobehaviour Actions

- src/gg.regression.unity.bots/Editor/Scripts/RGLegacyInputUtility/RGLegacyInputInstrumentation.cs
- src/gg.regression.unity.bots/Runtime/Scripts/ActionManager/Actions/MouseHoverObjectAction.cs
This is a second pass at addressing issues that can occur with the input instrumentation:
1. Check the `EditorApplication.isCompiling` and `EditorApplication.isUpdating` flags. If either is true, defer the instrumentation until later.
2. Remove the inner exception handler in InstrumentAssemblyIfNeeded (we already have exception handlers in the callers), and broaden the exceptions handled to all Exceptions (this will handle any errors that could come out of Mono.Cecil's own APIs).
I've tested this by re-opening Boss Room and some other Unity projects from scratch (deleting the Library folder). The whole instrumentation process works in my testing.
--- …
> [REG-1848] Address instrumentation conflicts and improve error handling

- src/gg.regression.unity.bots/Runtime/Scripts/ActionManager/RGActionManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/ActionManager/RGActionManagerSettings.cs
- src/gg.regression.unity.bots/Runtime/Scripts/GenericBots/RGMonkeyBot.cs
- src/gg.regression.unity.bots/Runtime/Scripts/GenericBots/RGMonkeyBotLogic.cs
- src/gg.regression.unity.bots/Runtime/Scripts/GenericBots/RGMonkeyBotLogic.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/BotActionJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/MonkeyBotActionDataJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/MonkeyBotActionDataJsonConverter.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotActionType.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/MonkeyBotActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/MonkeyBotActionData.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/SdkApiVersion.cs
This PR introduces a monkey bot segment that can be used with the bot segments system.
The segment has type name "MonkeyBot" and takes two parameters: action interval (rate at which to perform random actions) and action settings (this is the same settings object as used by the action manager and can be used to select the actions to exclude from the monkey bot).
I've tested this with Boss Room to create a sequence that first performs an input replay through the menus and then indefinitely runs a monkey test in-game. Here is an example bot segment file with the monkey bot segment:
[10.json](https://github.com/user-attachments/files/16256200/10.json)
Original draft PR (for reference): https://github.com/Regression-Games/RGUnityBots/pull/227
---
Find the pull request instructions …
> [REG-1859] Monkey bot segment

- src/gg.regression.unity.bots.ecs/Runtime/Scripts/StateRecorder/ECS/EntityObjectFinder.cs
- src/gg.regression.unity.bots/Runtime/Scripts/ActionManager/RGActionManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/BehaviourActionDataJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/BotActionJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/KeyFrameCriteriaJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/KeyFrameEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BehaviourActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/InputPlaybackActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/KeyFrameCriteria.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/KeyFrameCriteriaType.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/PartialNormalizedPathCriteriaEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/PartialNormalizedPathCriteriaEvaluator.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Samples.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Samples/SimpleRandomMovementBehaviour.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Samples/SimpleRandomMovementBehaviour.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/KeyboardEventSender.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/SdkApiVersion.cs
- Creates a sample exploring monobehaviour bot segment for one of our sample games
- Adds the ability to do partialNormalizedPath criteria
- Fixes a few bugs in the SDK around bot segments
- Sample bot segments are linked https://linear.app/regression-games/issue/REG-1862/playable-worlds-initial-bot-segments-for-blue-flower-test-steps-4
- Updates monobehaviour bot segment support to allow a maxRuntimeSeconds field
---
> [REG-1862] Partial Path Matching support + Sample Monobehaviour segment

- src/gg.regression.unity.bots/Editor/Scripts/RGLegacyInputUtility/RGLegacyInputInstrumentation.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGLegacyInputUtility/RGAssemblyResolver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGLegacyInputUtility/RGAssemblyResolver.cs.meta
This PR is to fix file in use errors that are still triggered by the instrumentation process in some games:
1. Add an assembly resolver RGAssemblyResolver, which stores all resolved assemblies in memory rather than holding onto a FileStream.
2. Dispose the assembly resolver when re-creating it.
---
> [REG-1848] Improvements to address file in use errors during instrumentation

- src/RGUnityBots/Assets/Resources/RGActionAnalysisResult.txt
- src/RGUnityBots/Assets/Scenes/ActionManagerTestScene.unity
- src/RGUnityBots/Assets/Scripts/ActionManagerTests/InputUtil.cs
- src/RGUnityBots/Assets/Scripts/ActionManagerTests/MouseBtnListeningObject.cs
- src/RGUnityBots/Assets/Scripts/ActionManagerTests/MouseMovementListeningObject.cs
- src/RGUnityBots/Assets/Scripts/ActionManagerTests/MouseRaycast2DObject.cs
- src/RGUnityBots/Assets/Scripts/ActionManagerTests/MouseRaycast3DObject.cs
- src/RGUnityBots/Assets/Tests/Runtime/RGActionManagerTests.cs
- src/gg.regression.unity.bots/Editor/Scripts/ActionManager/RGActionAnalysis.cs
- src/gg.regression.unity.bots/Editor/Scripts/RGEditorUtils.cs
- src/gg.regression.unity.bots/Editor/Scripts/RGLegacyInputUtility/RGLegacyInputInstrumentation.cs
- src/gg.regression.unity.bots/Editor/Scripts/RGLegacyInputUtility/RGLegacyInputSettingsPreprocessBuild.cs
- src/gg.regression.unity.bots/Runtime/Scripts/ActionManager/RGActionManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGLegacyInputUtility/RGBaseInput.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGLegacyInputUtility/RGLegacyEditorOnlyUtils.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGLegacyInputUtility/RGLegacyInputManagerSettings.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGLegacyInputUtility/RGStandaloneInputModule.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGUtils.cs
This PR addresses an issue where if Build Settings -> Player Settings -> Active Input Handling is set to “Input System Package (New)”, rather than “Both”, the SDK currently errors out due to a variety of dependency on both the old/new input systems throughout the SDK. This adds ENABLE_LEGACY_INPUT_MANAGER checks in all the remaining places where they should be to disable the legacy input usage when the game is exclusively using the new Input System.
As before, it is out of scope to fully remove dependency on the new Input System in the SDK for games that only use the legacy input system. This PR is just to ensure that the configurations of "Both" and "Input System Package (New)" are both working.
This was tested in two ways:
1. The unit tests in the RGUnityBots project were run with …
> [REG-1874] Support games whose active input handling is set to exclusively use the new Input System

- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlayCanvasV2.prefab
- src/gg.regression.unity.bots/Runtime/Scripts/ActionManager/RGActionManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseEventSender.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/VirtualMouseCursor.cs
- Changes our playback mouse cursor to be only a tiny dot and not the screen blocking williward head
- Hides the cursor on any run finish so that the cursor isn't stuck on the screen
- downsizes and re-centers the 'click highlight' so that we can more accurately see where the click occurred
https://github.com/user-attachments/assets/7b162867-88ca-467c-ad54-044a266a219d
---
> [REG-1882] Make virtual mouse cursor not messup CV analysis

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BehaviourActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotAction.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVImageMouseActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/IBotActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/InputPlaybackActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/MonkeyBotActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/RandomMouseObjectActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/RandomMousePixelActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- Adds API to hard stop bot actions when the User/UI requests a stop.  This is different than the 'soft' stop issued when a segment's criteria match that lets the current action finish before stopping
---
> [REG-1896] Hard stop (abort) segment actions from UI/user request

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/InputPlaybackActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/KeyboardEventSender.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseEventSender.cs
- Stops us from sending 2 events for the same key within the same frame
- Adds the current frame # to event send messages for clarity/debugging
- Test: Close in time, or even intentionally making the end before the start don't write in the same frame
---
> [REG-1884] Don't send 2 of same key in same frame

- src/RGUnityBots/Assets/Scenes/ActionManagerTestScene.unity
- src/RGUnityBots/Assets/Tests/Runtime/RGActionManagerTests.cs
- src/RGUnityBots/Assets/Tests/Runtime/RGLegacyInputSimulationTests.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGLegacyInputUtility/RGLegacyInputWrapper.cs
- src/gg.regression.unity.bots/Tests/TestFramework/Scripts/RGTestUtils.cs
This PR updates the unit tests for the action manager and legacy input support to be more precise and wait for the minimum amount of frames needed for actions to take place (previously, the tests were imprecise and waited for 2-4 frames with the hope that it was enough for the event processing to take place).
Changes:
1. Add the ability to manually invoke the update loop of the legacy input support, so that the tests can have more precise control over when the update happens.
2. Minimize the number of frames waited for as much as possible, and add comments indicating why extra frames are waited for. For tests about the new Input System, the tests now specifically wait for an update step to complete rather than waiting an arbitrary number of frames.
---
Find the pull request instructions …
> [REG-1883] Update action manager and legacy input unit tests to be more precise

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentsPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/BotSegmentJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/NormalizedPathCriteriaEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/PartialNormalizedPathCriteriaEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/KeyboardInputActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/SdkApiVersion.cs
- Fixes various SDK bugs / improvement areas found in blue flower testing
- Handles uncaught bot segment errors better by ending the bot segment
- Fixes a case where bot action errors weren't clearing their on screen error once they succeeded
- Removes unused `isPressed` field from KeyboardInputActionData
- Also re-orders the botsegment recording field order for easier editing
- Renames `keyFrameCriteria` to `endCriteria` (backwards compatible) for bot segments due to repeated mis-understanding of when those criteria are evaluated... Hopefully the new name helps self explain that this is the end condition for the segment. 
- Adds support for null/empty criteria bot segments
---
Find the pull request instructions [here](https://www.notion.so/regressiongg/Pull-Request-Process-0d57a7eb582a446 …
> [REG-1846] SDK Bug Fixes for Blue Flower Testing

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequence.cs
It just so happens that the BotSequences file got by without using any UnityEngine imports when used in the editor, but does rely on the import inside of builds. Added the missing import (this wasn't caught before because the lines that use this import are inside of `!UNITY_EDITOR` pragmas.
> [REG-1935] Add missing UnityEngine import

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/CVObjectDetectionEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/CVObjectDetectionEvaluator.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/CVServiceManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/KeyFrameCriteriaJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/KeyFrameEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVObjectDetectionKeyFrameCriteriaData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVObjectDetectionKeyFrameCriteriaData.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVService/CVObjectDetectionRequest.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVService/CVObjectDetectionRequest.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVService/CVObjectDetectionResult.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVService/CVObjectDetectionResult.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVService/CVObjectDetectionResultList.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVService/CVObjectDetectionResultList.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/KeyFrameCriteriaType.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/SdkApiVersion.cs
[Loom video](https://www.loom.com/share/7d55604f8e2c445daabbf32dab9569c5?sid=613050f0-da98-48c3-9078-fcb358121575).
Implemented the open vocab text query bot segment criteria. 
[Example segments on Boss Room.](https://github.com/Regression-Games/RGBossRoom/pull/67)
There are some follow up tasks that are related to this:
- [Refactor this and CV Image match evaluators.](https://linear.app/regression-games/issue/REG-1928/refactor-cv-object-detection-evaluator)
- [Update Python endpoints to match.](https://linear.app/regression-games/issue/REG-1920/update-python-object-detection-endpoints-to-match-sdk)
---
Every reviewer and the owner of the PR should …
> [REG-1913] Open vocab text query object detection bot segment criteria. 

- src/gg.regression.unity.bots.ecs/Runtime/Scripts/StateRecorder/ECS/EntityObjectFinder.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentZipParser.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentsPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/BehaviourActionDataJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/BotSegmentJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/CVImageMouseActionDataJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/KeyFrameCriteriaJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/MonkeyBotActionDataJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/RandomMouseObjectActionDataJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/RandomMousePixelActionDataJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Makes `apiVersion` field optional in Bot Segments
- Allows Zip files to contain both BotSegments and BotSegmentLists interleaved
- Properly sorts zip file entries
---
> [REG-1907] SDK Cleanup to Finalize Blue Flower Tests

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/CVObjectDetectionEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/CVServiceManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVObjectDetectionMouseActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVService/CVObjectDetectionRequest.cs
[Loom video.](https://www.loom.com/share/1bd67e94a1624c109b7a9a555251aa4c)
Related [Unity Boss Room example](https://github.com/Regression-Games/RGBossRoom/pull/69).
Implemented object detection criteria match using image query.
---
> [REG-1912] Implement bot segment criteria for open vocab image queries.

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/BotActionJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/CVObjectDetectionMouseActionDataJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotActionType.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVObjectDetectionMouseActionData.cs
[Loom video.](https://www.loom.com/share/a6657745b2674b7e8c08da81000b8503?sid=da3f217b-1e1d-4a7c-93a9-d38ccc057a13)
[Related Unity Boss Room example.](https://github.com/Regression-Games/RGBossRoom/pull/70)
Implement the bot segment action using image queries.
---
> [REG-1915] Implement bot segment action for clicking based on open vocab image queries.

- src/gg.regression.unity.bots/Runtime/Scripts/RGSettings.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/CVServiceManager.cs
- Update default endpoint for aiService to be production.  Empty or null string for the new config option will default to using the rgHostAddress
Developers can edit `RGSettings` scriptableObject asset in `Assets/Resources/RGSettings.asset` if they need to override this to `http://localhost:18888/` for local development.
---
> [REG-1879] Default configuration for AIService to prod

- src/gg.regression.unity.bots/Runtime/Images/AddIcon.png.meta
- src/gg.regression.unity.bots/Runtime/Images/CancelIcon.png.meta
- src/gg.regression.unity.bots/Runtime/Images/CardBackground.png.meta
- src/gg.regression.unity.bots/Runtime/Images/CardBackgroundDashed.png.meta
- src/gg.regression.unity.bots/Runtime/Images/CardInterior.png.meta
- src/gg.regression.unity.bots/Runtime/Images/CloseIcon.png.meta
- src/gg.regression.unity.bots/Runtime/Images/DeleteIcon.png.meta
- src/gg.regression.unity.bots/Runtime/Images/DragIcon.png.meta
- src/gg.regression.unity.bots/Runtime/Images/EditIcon.png.meta
- src/gg.regression.unity.bots/Runtime/Images/PlayIcon.png.meta
- src/gg.regression.unity.bots/Runtime/Images/ReloadIcon.png.meta
- src/gg.regression.unity.bots/Runtime/Images/SolidBackground.png.meta
- src/gg.regression.unity.bots/Runtime/Images/StackIcon.png.meta
- src/gg.regression.unity.bots/Runtime/Images/WilliwardFace.png.meta
- src/gg.regression.unity.bots/Runtime/Images/WilliwardFace_Ring.png.meta
- src/gg.regression.unity.bots/Runtime/Images/WilliwardOnLaptop.png.meta
- src/gg.regression.unity.bots/Runtime/Prefabs/HamburgerButton.png.meta
- src/gg.regression.unity.bots/Runtime/Prefabs/LoopButton.png.meta
- src/gg.regression.unity.bots/Runtime/Prefabs/PauseButton.png.meta
- src/gg.regression.unity.bots/Runtime/Prefabs/PlayButton.png.meta
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/CreateSequenceCard.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/DraggedCard.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/DropZone.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/PotientialDropSpot.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/SegmentCard.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/Sequence Editor.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlayCanvas.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/WarningButton.png.meta
- Went through the icons used in our UI and optimized the following:
- Anisotropic filtering levels: some of our pre-blurred art assets were being blurred further with more anisotropic filtering. Most of the icons should appear a bit clearer/crisper
- Removed any mipmapping for sprite assets. Apparently Unity is no good at generating mipmaps for sprites used in the UI, so we're just using raw image scaling for differing screen sizes. Much less blurred 👍🏻 
- Adjusting any pixel scaling. Some of our prefabs use the same assets at different scales. By adjusting these values we can make sure that edges are crisp at any size
- Set most of our sprites to use the `full rect` mesh type. Long story short, using the default mesh type of `tight` can result in the warping of images due to Unity …
> [Addison IF] Better sprite rendering

- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGBotManager.cs
- When I click the Williward face to open our overlay, the first click doesn't work and displays an error. Subsequent clicks produce no such error until the game/editor is restarted
- The `RGBotManager` script is shared by both the new and previous RGOverlay prefabs. The previous overlay initializes its Bot and Behaviour dropdowns when you first open the overlay; however, the new overlay does not need to populate these dropdowns. They don't even exist in the new overlay!
- In the future, when the new overlay becomes the standard, we can revise the RGBotManager script to contain no logic relating to Bot and Behaviour dropdowns
https://github.com/user-attachments/assets/121f3ee4-c9c2-456b-ae43-1a10f5e8cc58
> [FIX] prevent null exception when opening Overlay for the first time

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/CVImageCriteriaEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/CVObjectDetectionEvaluator.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVImageKeyFrameCriteriaData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVImageMouseActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/CVObjectDetectionMouseActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/PictureHelper.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/PictureHelper.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/SdkApiVersion.cs
- user-tools/README-CVImage.md
- CVImage actions/criteria now support the following options for `imageData`
- Base64 encoded jpg bytes (existing support)
- JPG or PNG file:// path (with extension)
- READABLE Texture2D (JPG/PNG/BMP/TIFF/etc) resource:// path (no extensions on resource paths)
- (https://docs.unity3d.com/Manual/ImportingTextures.html) 
- JPG or PNG .bytes raw resource:// path (no extensions on resource paths)
- this usage is uncommon, but you can save the image in your project as .bytes to keep it from being imported as a texture by Unity
---
Every reviewer and the owner of the PR should consider these points in their request (feel free to copy this checklist so you can …
> [REG-1967] Allow file and resource urls for cv image sources

- src/gg.regression.unity.bots/Editor/Scripts/ActionManager/RGActionAnalysis.cs
- src/gg.regression.unity.bots/Editor/Scripts/RGEditorUtils.cs
- src/gg.regression.unity.bots/Editor/Scripts/RGInstrumentation.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceManager.cs
- Resolves the hitch/hang experienced when entering play mode for a game with our SDK installed
- Botsequence resolution is now async
- Instrumentation code is back to being more performant
---
> [REG-1995] Fix the hitch/hang when starting a game with our SDK installed

- .gitignore
- src/RGUnityBots/Assets/Tests/Runtime/RGActionManagerTests.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentsPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseEventSender.cs
- Disables the 'real' mouse device before we click and re-enables it after we next unclick
- This may solve the issue where moving the real mouse during a click causes the click not to fire, but ONLY for behaviours listening for clicks.
- This DOES NOT solve the issue for UI elements as the UI system is processing the raw input system mouse movement events irrespective of whether that device is enabled or not.  It also assumes a single mouse pointer device and thus the movements of the real mouse effectively update the position of the virtual mouse as the UI input system sees things. Poor design on unity's part imho
- Cleans up when our VirtualMouse exists to only be while a replay is playing.  Before this was active all the time and might have interfered with their actual game logic for …
> [REG-1984] Cleans up virtual mouse device... doesn't solve UI real mouse interference

- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentsPlaybackController.cs
- Transient bot segments were completing too early in some cases (like Menu, play game, back to menu)... sometimes that second menu would be marked as complete too soon... see in code comments for more explanation
- Tested on boss room, menu -> select character -> load into game -> clear prompts -> exit to menu... for 105+ loops without failure.. so i believe this still covers the loading screen cases that transient criteria overlapping evaluations were originally put in for
---
> [REG-2006] Transient segments were completing too early

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentZipParser.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentsPlaybackContainer.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/KeyFrameType.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseEventSender.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseInputActionObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayToolbarManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Captures any outstanding logs/inputs/etc in a final state capture on end recording
- Only works on STOP recording from overlay button... if the application exits, we get notified too late by unity to be able to run a coroutine or wait for another frame :/ .  We still work in the case of application exit, we just don't get this extra data.
- Excludes any mouse events since the last button down IF this was a stop from our overlay button... this avoids replaying this sequence causing it to start recording again by clicking that button at the end
```json
{
"sessionId":"907c0645f3724b0b9454badd067b0fc2",
"referenceSessionId":null,
"apiVersion":13,
"tickNumber":2,
**"keyFrame":["END_RECORDING"],**
"time":7.7670521,
"timeScale":1,
"screenSize":{"x":1502,"y":796},
"performance":{ …
```
> [REG-2013] Record an END segment with any remaining inputs, logs, etc

- src/gg.regression.unity.bots/Runtime/Scripts/RGServiceManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/IStringBuilderWriteable.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverterContractResolver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/RGGameMetadataJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/RGGameMetadataJsonConverter.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/ObjectStatus.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/RGGameMetadata.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/RGGameMetadata.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/RecordingFrameStateData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/SdkApiVersion.cs
- Creates a metadata file with each recording
- (note: follow up task exists for adding endpoint to accept this upload on the backend)
- https://linear.app/regression-games/issue/REG-2033/add-endpoint-to-rgservice-to-capture-game-metadata
```json
{
"apiVersion":21,
"unityVersion":"2021.3.24f1",
"runtimePlatform":"WindowsEditor",
"isEditor":true,
"productName":"com.unity.multiplayer.samples.coop",
"companyName":"Unity",
"gameVersion":"2.0.4",
"gameBuildGUID":"",
"systemLanguage":"English",
"allConfiguredRenderPipelines":["UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset"],
"usingLegacyInputManager":true
}
```
- Adds some of the more dynamic metadata information to tick state payloads
```json
{
"sessionId":"67c5c4acc0c24a1fbd63a99bd0434e02",
"referenceSessionId":null, …
```
> [REG-2021] Add metadata file to recordings and add some info to state

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenshotCapture.cs
- Sets a correctly supported Graphics format on the screenshot texture for AsyncGPU readback on Mac Metal
---
> [REG-1988] Address Mac Metal async gpu format issues

- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlayCanvas.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlayCanvasV2.prefab
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentsPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BehaviourActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotAction.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/IBotActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/InputPlaybackActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseEventSender.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayToolbarManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Types/IRGBotSegmentActionBehaviour.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Types/IRGBotSegmentActionBehaviour.cs.meta
- src/gg.regression.unity.bots/Tests/TestFramework/Scripts/RGTestUtils.cs
- Allows the user to pause and resume bot sequence playback
- Handles updating the input playback time offsets appropriately when un-pausing
- Handles pausing any actions that implement the correct methods.
- Adds an interface that can be implemented by MonoBehaviours used in BotSegment actions to make them pausable
- Also works with replay looping
- Toggles between a new pause button and the play button to pause/un-pause
- Adds CTRL+SHIFT+F9 & CTRL+SHIFT+F10 shortcuts for play/pause & stop
---
Every reviewer and the owner of the PR should consider these points in their request (feel free to copy this checklist so you can fill it out yourself in the …
> [REG-2038] Allow pausing bot sequence playback

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/StringJsonConverter.cs
- ignores ASCII characters 0->7 and 14->27 when escaping json strings
- 0 - null
- 1 - start of heading
- 2 - start of text
- 3 - end of text (<- this was in traces from some games)
- 4 - end of transmission
- 5 - inquiry
- 6 - acknowledge
- 7 - bell
- 14 -> 27 (see online ascii table)
---
> [REG-2043] Ignore control characters in text strings

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
Our current automatic replay copying fails if the BotSegment/Sequences folder is not present. This PR ensures those folders are created, and present.
Tested in Editor and Build.
[Loom video](https://www.loom.com/share/f9e70481e2f842a0b6e298508a66d2ed)
---
> [REG-2056] Ensure BotSegment/Sequence directories are created while saving replays.

- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceEditor.cs
- Fix recording copy of underlying segments
---
> [REG-2060] Fix recording copy of underlying segments

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Handle refreshing assets after copying segments into project when running in the editor
---
> [REG-2059] Refresh assets after copy of recording if in unityeditor

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
[Loom Video](https://www.loom.com/share/1fe8e487f74e4a78abf47a8cc374563f?sid=dd98d33b-a5b0-4f45-b952-76110476a312)
Currently when we are creating a BotSequence from the copied bot segments the segments are sorted alphanumerically. This means that 2.json will come after 19.json, breaking the sequence.
This PR hotfixes it by ordering it numerically. 
We should do the same sorting order wherever we are showing segments.
> [REG-2061] When creating a bot sequence from the Latest Recording sort the segments numerically. 

- src/gg.regression.unity.bots/Runtime/Scripts/RGHeadlessSequenceRunner.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGHeadlessSequenceRunner.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequence.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/KeyboardEventSender.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseInputActionObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayToolbarManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/Types/PlaybackResult.cs
- src/gg.regression.unity.bots/Tests/TestFramework/Scripts/RGTestUtils.cs
- Adds -rgsequencepath command line option
- This allows you to start Unity , automatically run an RG bot sequence, and then exit the unity runtime
- Also supports -rgsequencetimeout option to put a number of seconds limit on your runtime before it closes Unity and reports a failure
- Supports RC=0 for successful run and RC=1 for timeout failure and RC=# for various arg parsing errors
- Fixes some cases for -batchmode where keyboard and mouse devices needed to handle being null, and/or needed a virtual keyboard device registered to function correctly 
Usage samples
- Run the game with the full on screen graphics
- Supports ALL of our SDK features
- `./com.unity.multiplayer.samples.coop.exe -rgsequencepath "Assets/RegressionGames/Resources/BotSequences/TypeADF.json" -rgsequencetimeout 7`
- …
> [REG-2063] Enable running unity with -rgsequencepath startup option

- src/gg.regression.unity.bots/Runtime/Fonts/Regression.asset
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/SegmentCard.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/Sequence Editor.prefab
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGDraggableCard.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceEditor.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentsPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/BotSequenceEntryJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegmentList.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequence.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequenceEntry.cs
- src/gg.regression.unity.bots/Tests/Scripts/RGOverlay/RGDraggableCard.test.cs
- Handles dis-ambiguating segments that have the same 'name' but different paths on the editor UI
- If the segment has a name, then the name and path will be shown
- If the segment DOES NOT have a name, then the path will be shown in place of the name, but the path sub text will be hidden
- Makes needed updates to the prefab to make decription/overlow expansion respect this new layout
- Stops setting the 'resourcePath' as the name on segments/segmentLists loaded from sequences and tracks the resourcePath separately.  This allows us to know if a user supplied name was truly set or not.
Long descriptions example with ...
Empty name example
---
Every …
> [REG-2068] Handle ambiguous available segments in SequenceEditor UI by showing path

- src/gg.regression.unity.bots/Runtime/Scripts/RGHeadlessSequenceRunner.cs
Currently we log a:
```
{{RG}} 2024-10-04T11:57:48:9937 ERROR [1] --- -rgsequencetimeout command line argument requires -rgsequencepath to also be specified
UnityEngine.Debug:LogError (object)
RegressionGames.RGDebug:LogToConsole (string,RegressionGames.RGDebug/RGLogLevel,UnityEngine.Object) (at C:/Users/batu_regression/Desktop/reg/RGUnityBots/src/gg.regression.unity.bots/Runtime/Scripts/RGDebug.cs:146)
RegressionGames.RGDebug:LogError (string,UnityEngine.Object) (at C:/Users/batu_regression/Desktop/reg/RGUnityBots/src/gg.regression.unity.bots/Runtime/Scripts/RGDebug.cs:64)
RegressionGames.RGHeadlessSequenceRunner:ParseTimeoutArgument () (at C:/Users/batu_regression/Desktop/reg/RGUnityBots/src/gg.regression.unity.bots/Runtime/Scripts/RGHeadlessSequenceRunner.cs:143) …
```
> [REG-2089] Fix timeout path validation check

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
I'm not very happy with this PR... I cannot determine if it fixes the original issue because while we were able to reproduce the bug on Wednesday afternoon, as of Thursday I was **not** able to reproduce the issue... Also, this works as expected when in the editor, but in the build, the sequence is not created correctly (the segments and sequence are not created). I have a feeling that the build issue is unrelated to this particular PR.
I am opening this as a draft and would like to chat with @batu and @addisonbgross about this perhaps?
UPDATE (Oct 8th, Mon afternoon) - I've now updated this to use the File.Copy function, but once again, I won't be able to determine if this fix works until we try it out with the user.
> [REG-2064] Manually write files on OSX platforms

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/KeyboardEventSender.cs
- src/gg.regression.unity.experimental.runespawn/Editor/Scripts/EditorCommandServer.cs
- src/gg.regression.unity.experimental.runespawn/Editor/Scripts/PlayModeController.cs
[Python side component.](https://github.com/Regression-Games/Runespawn/pull/10)
I tried to be mindful of unsubscribing events, but I don't know if what I ended up with is the right way to do it.
I ended up simply writing the code myself instead of using our built in log detailing as it was as simple as: 
`_logs.Add($"[{type}] {logString}");`
I also made KeyboardEventSender default log level from info to debug, as it would clog up the LLM context.
---
> [REG-2110] Implement the GetRuntimeLogs command in the Runespawn server.

- src/gg.regression.unity.bots/Runtime/Scripts/RGHeadlessSequenceRunner.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequence.cs
There was a bug where sequences and segments could not be loaded from the application data path in builds. I am not super familiar with all of the logic here so wanted to take a minute to explain my observations and decisions here:
* I was getting errors like this in **production builds**: `Error reading Bot Sequence /Users/aaronvontell/Library/Application Support/DefaultCompany/normal/RegressionGames/Resources/BotSequences/Latest_Recording.json: System.Exception: Invalid path.  Path must be relative, not absolute in order to support editor vs production runtimes interchangeably.`
* In the editor, paths look like `Assets/RegressionGames/Resources/BotSequences/asdasd.json`
* When in a build, the paths look like `/Users/aaronvontell/Library/Application …
> [REG-2105] Allow absolute paths to be used in segment and sequence loading

- src/gg.regression.unity.bots/Runtime/Scripts/RGHeadlessSequenceRunner.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RemoteOrchestration/RGRemoteWorkerAssignmentManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentsPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/LoggingObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- When running a remote work assignment, the SDK will now only capture log statements, not state/images/etc
- This utilizes the fact that a remote work assignment is active, not any startup args.. Thus if you use this system with the overlays it will still behave normally
- Fixes some bugs managing the replay button bar states that were recently introduced
- Removes some un-used code
- Fixes a bug where directories weren't getting clean up correctly after zipping
---
> [REG-2125] Only capture logs when running a remote work assignment

- src/gg.regression.unity.experimental.runespawn/Editor/Scripts/PlayModeController.cs
[Main Python side PR.](https://github.com/Regression-Games/Runespawn/pull/16)
- This PR adds an extra '\n' between errors for easier splitting.
- This PR also adds capturing of warnings.
> [REG-2126] Collapse multiline error logs in Runespawn.

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/TransformObjectFinder.cs
- Updates the bounds computation for world space transforms to consider whether their renderer is within ANY camera's view frustrum before including them in the state
---
> [REG-2130] Exclude transform renderers outside the view frustrum

- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSegmentEntry.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentsPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequence.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayToolbarManager.cs
- Fixes a bug where the replay toolbar wasn't always reset to the correct button states on succesful workAssignment completion
- Fixes a bug where the activeSequence status was incorrect because the activeBotSequence was getting cleared accidentally right after it was set
- Refactored some very confusingly named methods to avoid this happening again !
---
> [REG-2153] Fix/Harden Remote workAssignments managing active sequence states

- src/RGUnityBots/Assets/RegressionGames/Resources/RGBotSequences.asset
- src/RGUnityBots/ProjectSettings/EditorBuildSettings.asset
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentsPlaybackController.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/IKeyFrameCriteriaData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/InputPlaybackActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/KeyFrameCriteria.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/InputData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseEventSender.cs
- src/gg.regression.unity.bots/Runtime/Scripts/Types/PlaybackResult.cs
- src/gg.regression.unity.bots/Tests/Scripts/ActionManager/RGActionManagerTests.cs
- src/gg.regression.unity.bots/Tests/Scripts/BotSegments.meta
- src/gg.regression.unity.bots/Tests/Scripts/BotSegments/BotSegmentsTests.cs
- src/gg.regression.unity.bots/Tests/Scripts/BotSegments/BotSegmentsTests.cs.meta
- src/gg.regression.unity.bots/Tests/Scripts/GameScene/GameSceneTests.cs
- src/gg.regression.unity.bots/Tests/Scripts/RGOverlay/RGCreateNewSequenceButton.test.cs
- src/gg.regression.unity.bots/Tests/Scripts/RGOverlay/RGDeleteSequence.test.cs
- src/gg.regression.unity.bots/Tests/Scripts/RGOverlay/RGDraggableCard.test.cs
- src/gg.regression.unity.bots/Tests/Scripts/RGOverlay/RGDraggedCard.test.cs
- src/gg.regression.unity.bots/Tests/Scripts/RGOverlay/RGSegmentEntry.test.cs
- src/gg.regression.unity.bots/Tests/Scripts/RGOverlay/RGSequenceEditor.test.cs
- src/gg.regression.unity.bots/Tests/Scripts/RGOverlay/RGSequenceEntry.test.cs
- src/gg.regression.unity.bots/Tests/Scripts/RGUtilsTests.cs
- src/gg.regression.unity.bots/Tests/Scripts/TestHelpers.cs
- src/gg.regression.unity.bots/Tests/Scripts/TestHelpers.cs.meta
- src/gg.regression.unity.bots/Tests/TestFramework/Scripts/RGTestUtils.cs
- Adds APIs to our RGTestUtils to allow users to think about their Unity tests in terms of our BotActions and BotCriteria
- Allows running a bot segment or bot segment list (in addition to the existing sequence support we had)
- (I put these in to unlock the use of CV or other powerful criteria types in regular unity tests)
- Allows running a bot action as a standalone test step
- Allows waiting for bot criteria as a standalone test step
- Adds test with actions and criteria (this was hard to get right with the setup needed based on which input system and which event system was in use)
- Moves some test code to a more appropriate location 
- Hardens some code around inputData to make this easier and allow null/non-set fields instead of requiring empty objects 
- TODO: Will need to create …
> [REG-2145] Add test APIs for using bot segments, actions, and criteria

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/JsonConverters/BotSegmentJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayToolbarManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Fixes various bugs encountered during PW remote worker play button test
- Fixes a bug where remote work assignments weren't ending cleanly due to a mis-timed clearing of the complete success status
- Allows for parsing empty/null botAction in segments to make actionless segments easier to write
---
> [REG-2166] [REG-2165] [REG-2164] Fix remote worker bugs from PW play test

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Fixes some lingering thread safety issues on end recording that were now leading to infinite loop at teardown based on changes in the previous PR
- Changes to tokensource in last pr undone/re-imagined in this PR
---
> [REG-2169] Fix some long lingering thread safety issues at end of recording

- src/gg.regression.unity.bots/Runtime/Scripts/RGHeadlessSequenceRunner.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegmentList.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequence.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequenceEntry.cs
- The loading code changes to mark `isOverride` on objects as they are loaded ... enables REG-2005 UI work
---
> [REG-2005] part 1 - Mark 'isOverride' on segments/sequences as they are loaded

- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/DraggedCard.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/DropZone.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/PotientialDropSpot.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/SegmentCard.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/Sequence Editor.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlayCanvas.prefab
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/Animation/RGImagePulseAnimation.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/Animation/RGImagePulseAnimation.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGDraggableCard.cs
https://github.com/user-attachments/assets/5bdb08ff-c3c0-4598-9c38-154d21c7f6d9
Here are some general, visual improvements for the Sequence Editor. I've tried to make it more spacious, and the text a bit easier to read. I was unable to find a good way to have the Sequence Editor stretched near the edges of the viewport, while still maintaining the scrollable lists within it. This would be a good improvement to make in the future if we get some traction
**No functional changes**
- Larger Sequence Editor in general
- Taller list of Segments in the Sequence
- Taller list of Available Segments
- Larger text for pretty much everything in there
- The Potential Drop Spot prefab now pulses the opacity of its child image. I thought this made it a bit more apparent 👀 
- Some improvements to dynamic …
> [REG-2071] Increase the dimensions of the Sequence Editor

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/StringJsonConverter.cs
- When attempting to record gameplay in this [Vampire Survivors Clone](https://matthiasbroske.github.io/vampire-survivors.html), an error occurs that prevents the recording from happening
- When writing our game state to JSON during gameplay recording, we get an index out of bounds error when checking if individual chars in the game state need to be escaped
- This game uses Mandarin characters, even when you use the English language setting, and these Mandarin characters were causing the index out of bounds error
- We solve this error by being able to check if a char needs to be escaped, and handling any standard Unicode character (ie: codes \u0000 to \uFFFF)
- The `char.MaxValue` == `\uFFFF`
https://www.loom.com/share/e4302d036acf448f9a1bc3ae3ce42393
> [FIX] Avoid index out of bounds error when escaping chars

- src/gg.regression.unity.bots/Editor/Scripts/RGInstrumentation.cs
- Fixes a using issue on games not using legacy input system
- Recreated and Tested on BossRoom by updating project settings for input from 'both' to 'new only'
---
> [REG-2187] Fix compile issue when NOT using legacy input

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayToolbarManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- One of the next steps in moving towards the eventual removal of loading recordings from a zip file
- Saves the recording/replay data correctly to Unity's persistent path for the application
- Sets the default file path for the replay zip file loader to go to this new path
- Adds seconds to the name of the recording folders to remove ambiguity when doing multiple small recordings quickly
See doc update https://github.com/Regression-Games/RegressionDocs/pull/104
---
> [REG-2044] Save/Load recording zips to default persistent path

- src/gg.regression.unity.bots/Editor/Scripts/ActionManager/RGActionAnalysis.cs
- Dramatically shortens the time required to analyze game actions
- Loads scenes in preview instead of actually modifying the loaded scenes in the editor (this is both for performance and functional to not mess with the user's editor state)
- Caches type field/property resolutions
- Reduces 'new' object allocations/gc and prefers re-use
- Fixes various code style warnings in the analysis file
- Optimizes the multi loop code analyzer that always ran at least 2 passes to only run >1 passes when necessary
- Confirmed with Beyond Compare text on a large customer project that before and after results are equivalent
- Uses multithreading to run resource analysis and code analysis in parallel (also parallelizes parts of code analysis itself)
- Still provides detailed status/cumulative-progress …
> [REG-2191] Speedup game action analysis

- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlayCanvas.prefab
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceEntry.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGUtils.cs
In an effort to improve our demos to potential clients building mobile games, I've made the UI a bit larger when running on a mobile device. This is definitely not a comprehensive solution, but it is a small win.  
- We can detect when a game is running on a mobile device, or in the Unity Device Simulator
- When on mobile or using the Unity Device Simulator:
- Scale everything in our UI to be larger 
- Disable the edit, copy, and delete actions for Sequences
- Hide the 'create sequence button'. Creating or editing Sequences on mobile is too cramped
- When the Unity viewport is in a portrait orientation:
- Scale everything in our UI to be larger 
These were taken on my old OnePlus 7. Tested with both our [Match3Example](https://github.com/Regression-Games/Match3Example) game, and the …
> [REG-2194] Improved SDK UI on mobile

- src/gg.regression.unity.bots/Editor/Scripts/RGEditorUtils.cs
A very quick QOL improvement for both us and developers who want to dive deeper into the raw data collected by our systems - simply adds a menu item that will open the folder containing the recordings from our SDK.
I only tested this on Mac, but I have been told through my forum reading that this also works on Windows.
> [REG-2195] Ability to easily open data recording location

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentDirectoryParser.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/StringJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseEventSender.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseInputActionObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/TransformObjectFinder.cs
- Fixes (makes less likely) / catches a string json escaping buffer overflow bug during log capture on some games
- Updates mouse observation to record all objects at a point, not just UI objects if a UI object is hit
- Fixes a case where URP with multiple cameras (base + N overlays) wasn't considering the screenSpace correctly for overlay cameras
---
> [REG-2193] Fixes issues with capture mouse across different game architectures
