Regression-Games/RGUnityBots

- Editor/Scripts/ReplayModelManager.cs
- Runtime/Scripts/RGBotConfigs/RGState.cs
- Runtime/Scripts/RGFindUtils.cs
- Runtime/Scripts/RGIconPulse.cs
- Runtime/Scripts/RGOverlayMenu.cs
Added namespaces:
* RGState
* RGFindUtils
Fixed namespaces:
* RGIconPulse
* ReplayModelManager
> [REG-1206] Namespace the SDK

- Runtime/Scripts/RGSettings.cs
> [REG-1199] Update the defaults for SDK settings to be prod

- Runtime/Prefabs/ActiveBotEntryNew.prefab
- Runtime/Prefabs/RGOverlayCanvas.prefab
- Runtime/Scripts/RGOverlayMenu.cs
> [REG-1093] Add "Stop All" button to RGOverlay

- Runtime/Scripts/RGAgentTypes.meta
- Runtime/Scripts/RGBotServerListener.cs
- Runtime/Scripts/RGEnvVars.cs
- Runtime/Scripts/RGEnvVars.cs.meta
- Runtime/Scripts/RGServiceManager.cs
Adds a few features to the SDK to support CI/CD usage.
* A new "HasBotsRunning()" function that is used during tests to figure out when to terminate (see other PR at end of this description for an example)
* Adds API Key and Host env vars that can override the project settings in CI/CD
Example: https://github.com/Regression-Games/RGUnitySample/pull/6
> [REG-1099] Utils and env vars for CI/CD

- Runtime/Scripts/RGBotServerListener.cs
- Runtime/Scripts/RGServiceManager.cs
- Fixes an issue where CPU bot actions were being routed to the human player by accident
- Fixes an issue where the Auth call was erroneously including the previous Auth token header
> [REG-1241] Fix a bug where agents were being mis-mapped to human players

- Runtime/Scripts/RGBotServerListener.cs
- Runtime/Scripts/RGDebug.cs
- Runtime/Scripts/RGServiceManager.cs
- Makes various async fixes /tweaks
> Attempt to fix CI

- Editor/Scripts/CodeGenerators/GenerateRGStateClasses.cs
- Editor/Scripts/CodeGenerators/GenerateRGStateClasses.cs.meta
- Editor/Scripts/CodeGenerators/RGActionCodeGenerator.cs
- Editor/Scripts/RGStateInfo.cs
- Editor/Scripts/RGStateInfo.cs.meta
- Editor/Scripts/RGStatesInfo.cs
- Editor/Scripts/RGStatesInfo.cs.meta
- Runtime/Scripts/Attributes/RGStateAttribute.cs
- Runtime/Scripts/Attributes/RGStateAttribute.cs.meta
- Runtime/Scripts/RGBotConfigs/RGState.cs
Define RGStates through an attribute:
1. Public fields
```
[RGState]
public int myVariable;
```
2. Public getter methods. (No parameters)
```
[RGState]
public int GetVariable() { return myVariable; }
```
Override the name of the state by passing in a string to the attribute
```
[RGState("My State")]
public int foo;
```
```
[RGState("My State")]
public int GetFoo() { return foo;}
```
Once the attributes are added, run `Regression Games -> Generate Scripts` from the menu
Generated State script will go to `Assets/RGScripts/RGStates/`
Add the state scripts to the GameObject and fill out the inspector fields for `isPlayer`, `objectType`, `isRuntimeObject`, and position/rotation sync
> [REG-1232] Prototype, design, and implement a new RGState approach that uses attributes

- Editor/Scripts/CodeGenerators/RGActionCodeGenerator.cs
Creates `RegressionGames.zip` in project folder when files are generated
> [REG-1267] Unity / Agent Builder Crossover: Export actions and state

- Runtime/Scripts/RGBotLocalRuntime/RG.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotRunner.cs
- Runtime/Scripts/RGBotServerListener.cs
- Runtime/Scripts/StateActionTypes/RGStateEntity.cs
- SampleBots.meta
- SampleBots/BossRoom.meta
- SampleBots/BossRoom/AbilityBot_0.meta
- SampleBots/BossRoom/AbilityBot_0/BotEntryPoint.cs
- SampleBots/BossRoom/AbilityBot_0/BotEntryPoint.cs.meta
- SampleBots/BossRoom/AbilityBot_0/BotRecord.asset
- SampleBots/BossRoom/AbilityBot_0/BotRecord.asset.meta
- SampleBots/BossRoom/MenuAbilityBot_1.meta
- SampleBots/BossRoom/MenuAbilityBot_1/BotEntryPoint.cs
- SampleBots/BossRoom/MenuAbilityBot_1/BotEntryPoint.cs.meta
- SampleBots/BossRoom/MenuAbilityBot_1/BotRecord.asset
- SampleBots/BossRoom/MenuAbilityBot_1/BotRecord.asset.meta
- Adds sample bots for BossRoom
- Adds to the `RG` APIs to enable Menu Bots
> [REG-1291] Provide sample bots

- Editor/Scripts/RGTickInfoActionManager.cs
- Runtime/Prefabs/RGOverlayCanvas.prefab
- Runtime/Scripts/RGBotConfigs/RGButtonState.cs
- Runtime/Scripts/RGBotConfigs/RGClickButtonAction.cs
- Runtime/Scripts/RGBotServerListener.cs
- Runtime/Scripts/StateActionTypes/RGStateEntity.cs
Unbreaks everything broken by RGEntity PRs
See also https://github.com/Regression-Games/RGBossRoom/pull/35
Also fixes replay data....
> Unbreak everything

- Editor/Scripts/CodeGenerators/CodeGeneratorUtils.cs
- Editor/Scripts/CodeGenerators/CodeGeneratorUtils.cs.meta
- Editor/Scripts/CodeGenerators/GenerateRGActionClasses.cs
- Editor/Scripts/CodeGenerators/GenerateRGActionMapClass.cs
- imgs.meta
- Sanitizes all special characters out of action name strings and replaces with `_`
- I played with trimming out the characters instead of replacing them, but that led to more frequent name conflicts in testing
- Input
```csharp
[RGState("1Some-/=+Sta7e 3 World")]
public bool someState;
[RGAction("1Perform-/=+At7ack 3 Now")]
public void PerformAttack(bool isEnabled, string actionName, int attackNumber, float damageAmount)
{
}
```
- Output [RGAction]
```csharp
/*
* This file has been automatically generated. Do not modify.
*/
using System;
using System.Collections.Generic;
using RegressionGames;
using RegressionGames.RGBotConfigs;
using RegressionGames.StateActionTypes;
using UnityEngine;
using Unity.BossRoom.Gameplay.Actions;
namespace RegressionGames
{
public class …
```
> [REG-1338] Sanitize action name strings

- Editor/Scripts/BotManagement/RGBotSynchronizer.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotAssetRecord.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotAssetsManager.cs
- Runtime/Scripts/RGBotLocalRuntime/RGBotRuntimeManager.cs
- Runtime/Scripts/RGServiceManager.cs
- Runtime/Scripts/Types/RGBotCodeDetails.cs
- Runtime/Scripts/Types/RGBotCodeDetails.cs.meta
- Runtime/Scripts/Types/RGClientConnection_Remote.cs
- Runtime/Scripts/Types/RGCreateBotRequest.cs
- Runtime/Scripts/Types/RGCreateBotRequest.cs.meta
- Implements synchronization of RG bots between local and remote servers
- Depends on: https://github.com/Regression-Games/RegressionGames/pull/420
> [REG-1306] Synchronize Unity Bots With RG Server

- README.md
Finally adds a proper version to our download instructions so that users don't get stuck with rapidly-changing main. 
A PR has also been opened for the main docs.
> [REG-1310] Add proper version to getting started

- Editor/Scripts/CodeGenerators/GenerateRGActionClasses.cs
```csharp
try
{
if (newZeroInput is Vector2 value)
{
newZero = value;
}
else
{
newZero = RGSerialization.Deserialize_Vector2(newZeroInput.ToString());
}
}
catch (Exception ex)
{
RGDebug.LogError($"Failed to parse 'newZero' - {ex}");
}
```
> [REG-1379] Handle type checks for local unity bots

- Runtime/Scripts/RGBotLocalRuntime/RGBotRuntimeManager.cs
- In my sick/tired stupor, I missed pushing my last commit :(
> [REG-1401] fix fallback namespace code

- Editor/Scripts/Startup/RegressionPackagePopup.cs
**Changes**
* Updated Docs URL
* Fixed paths to work on both Windows and Mac
**To Test**
1. Create new URP Project on Mac
2. Import SDK
3. Hit "Continue as Guest"
4. Hit "Import Sample" and verify it opens
5. Create new URP Project on PC
6. Import SDK
7. Hit "Continue as Guest"
8. Hit "Import Sample" and verify it opens
> [REG-1404] Fix Windows Sample Import

- Editor/Scripts/CodeGenerators/BuildAutoProcessor.cs
- Editor/Scripts/CodeGenerators/BuildAutoProcessor.cs.meta
- Editor/Scripts/CodeGenerators/RGCodeGenerator.cs
- Auto generates RG SDK attribute classes on any code change (whenever the editor would normally recompile scripts).
- Does not run on SDK internals changes
- Does not run for changes to files in the generated scripts folder
- Removes the manual option for generating classes
- Updates the error handling in the code generator to better indicate a user issue (WARNING) vs an RG SDK bug (ERROR)
- Displays a prompt to the user and a log message when code generation or extracting fail
- Addresses REG-1464
---
Every reviewer and the owner of the PR should consider these points in their request (feel free to copy this checklist so you can fill it out yourself …
> [REG-1478] [REG-1464] Auto generate RG SDK classes

- Editor/Scripts/CodeGenerators/RGCodeGenerator.cs
- Runtime/Scripts/Attributes/RGStateAttribute.cs
- Allows using [RGState] on class properties like 
```csharp
[RGState]
public InventorySystem Inventory => m_Inventory;
```
---
> [REG-1508] Support RGState on class properties

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/RecordingAndReplayContainerTypes.cs
- Fixes a bug in the json format for input
---
> [REG-1659] Fix input json format

- src/gg.regression.unity.bots/Editor/Scripts/RGOverlay/IRGBotFinder.cs
- Fixes build errors for production runtime
- With this fix, I have been able to confirm that the new bossroom sample bots work in production runtime
---
> [REG-1424] Fix runtime build compilation error

- src/gg.regression.unity.bots/Runtime/Prefabs/RGBotEntry.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlayCanvasV2.prefab
Updated `OverlayCanvasV2` prefab and `RGBotEntry` prefab to correctly resize on all screen sizes
---
> [REG-1667] Fix overlay resizing

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/DecimalJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/DoubleJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/FloatJsonConverter.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/KeyboardInputActionObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/MouseInputActionObserver.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/RecordingAndReplayContainerTypes.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- Fixes an issue where 'null' endTime on keyboard input was serialized correctly
- Fixes an issue with the inputsystem check
---
> [REG-1685] Fix keyboard endtime and input system check

- README.md
This is a preliminary PR for improving the README of the Unity package, at least enough to more closely reflect the current state of things. By the end of the month for our MVP launch, this will likely be updated again to have more information.
I might also start a form or table in notion soon for us to name this thing... Regression Games Unity Bots is kind of a mouthful. I wonder if we can find a descriptive name and tagline that gets the idea across but is more memorable.
---
> Update README to be more accurate

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataContainer.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayDataPlaybackController.cs
- Handles UI elements/scenes and gameObject elements/scenes separately as far as key frame validation on replay... makes things like the BossRoom loading screen where the timing of things loading is non-deterministic not fail anymore (tested about 12 times across 3 bossroom/unity launches and saw no instances of the loading screen replay hangs)
- Removes keyframe validation of specificGameObject paths as this was causing un-necessary complexity and instability... that information is still used for mouse clicking though
- An example from bossroom showing the (UI:GameElement) tick wait interleaving on scene load... sometimes the UI is ahead, sometimes the GameElements are ahead
---
Find the pull request instructions [here](https://www.notion.so/regressiongg/Pull-Request-Process-0d57a7eb582a4 …
> [REG-1678] Track UI and game object matching separately in replays

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Readback GPU data asynchronously when capturing screenshots to avoid slowing down keyframes in the game
- Gives a 10+ms reduction in frame-time impact for recording keyframes because the main thread no longer has to wait for the screenshot data before continuing
BEFORE
AFTER
---
> [REG-1717] Async GPU Readback for Screenshots

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Still going to get spammed with an error every screenshot on Mac (thanks Unity).. but colors will now be corrected for Metal on Mac
---
> [REG-1735] Fix mac screenshot colors

- src/gg.regression.unity.bots/Editor/Scripts/Startup/RegressionPackagePopup.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGServiceManager.cs
Updates the relevant docs links in the package to use the URLs. Also, adds a slightly more relevant first box in the welcome screen.
> Update docs links and getting started description

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/JsonConverters/StringJsonConverter.cs
- Handle mapping for special chars like 'TM'
---
> [REG-1748] Handle mapping for special chars like 'TM'

- src/gg.regression.unity.bots/Editor/Scripts/RGLegacyInputUtility/RGLegacyInputInstrumentation.cs
- Avoids setting up the assembly resolver N times
- See [Linear](https://linear.app/regression-games/issue/REG-1806/fix-legacyinput-instrumentation-performance) for screenshot of performance and GC issue before this change
- This update changes it so that the AssemblyResolver is only created once per compile instead of once per assembly
---
> [REG-1806] Fix LegacyInputInstrumentation performance

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/Collider2DRecordState.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/ColliderRecordState.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/Rigidbody2DRecordState.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/RigidbodyRecordState.cs
- add name fields to collider and rigidbody components
---
> [REG-1854] Add collider and rigidbody names to state

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/TransformObjectFinder.cs
- Fix parentId objects not being in state recording
---
> [REG-1863] Fix parentId objects not being in state recording

- src/gg.regression.unity.bots/Runtime/Scripts/RGServiceManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/Types/RGCreateBotInstanceRequest.cs
[Backend PR](https://github.com/Regression-Games/RegressionGames/pull/517)
[Client PR](https://github.com/Regression-Games/RegressionClient/pull/532)
---
> update bot-instance API paths

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/InputPlaybackActionData.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/Models/InputData.cs
- Interleaves mouse and keyboard inputs from a segment by time
---
> [REG-1900] Input playback mouse keyboard interleaving

- .github/workflows/unity-build.yml
- Adds concurrency flags to build workflow
---
> Add concurrency to unity build workflow

- src/gg.regression.unity.bots/Runtime/Scripts/ActionManager/README.md
- src/gg.regression.unity.bots/Runtime/Scripts/GenericBots/Experimental/ActionManagerGPTBot.cs
- src/gg.regression.unity.bots/Runtime/Scripts/GenericBots/Experimental/ActionManagerGPTBot.cs.meta
This adds a simple example of a MonoBehaviour bot that uses the action manager to generate an LLM prompt defining the game rules (in terms of the set of discrete actions available) and then evaluating the LLM response during gameplay into actual keyboard/mouse inputs.
The LLM is prompted with the user-provided context and the set of discrete actions available (as identified by the action analysis). Each action is assigned a name based on its input-handling API identified in the code (e.g. "Button 'Jump'", "Key.RightArrow"). The LLM is requested to generate a sequence of N actions for a user-specified task that choose from among the actions in this discrete action space.
If given the default task of `Conduct exploratory testing like a quality assurance tester`, the bot moves left/right …
> [REG-1905] Add action manager LLM bot example

- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/SequenceCard.prefab
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGBotManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceEntry.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayToolbarManager.cs
- Enabled the play button on the Bot Sequence Card to actually start the Sequence
- Ensured that the RGOverlay is in the correct state upon starting a Sequence
https://www.loom.com/share/bfa22fdc15ff44c5b8ec32f5e2914354
> [REG-1906] Start Sequences from Sequence overlay

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BehaviourActionData.cs
- Handle failing behaviour segments that dont load or timeout
---
> [REG-1975] Handle failing behaviour segments that dont load or timeout

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayToolbarManager.cs
Note this loom was recorded for the V2 canvas, but Addison's new canvas uses the same logic. I confirmed my changes work the same way for the new one as well.
https://www.loom.com/share/004a60a1a2e34c9b8df39fb8ade1a8e0?sid=9bdccb0d-c60b-496f-93b3-e5f1666d1665
---
> [REG-1970] Reload zip contents on play

- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequence.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ReplayToolbarManager.cs
https://www.loom.com/share/d06cf72714f94b9ba3e4f288e7e98c09
---
> [REG-1978] determine segment types when we load them from disk

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequenceEntry.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/SdkApiVersion.cs
- Fixes failed merge for version of sdk
---
> [REG-1963] fix merge version issue

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/CVImageCriteriaEvaluator.cs
- Corrects misuse of Unity File in using statement to use proper System File in the using  (<- yes I wrote this on purpose.. you're welcome)
---
> [REG-2002] Incorrect File using was breaking production builds

- src/gg.regression.unity.bots/Runtime/Scripts/ActionManager/RGActionManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGLegacyInputUtility/RGLegacyInputWrapper.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGLegacyInputUtility/RGStandaloneInputModule.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGUtils.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/BotSegmentsPlaybackController.cs
- src/gg.regression.unity.bots/Tests/Scripts/LegacyInput/RGLegacyInputSimulationTests.cs
- Updates our code for managing our legacy input overrides... tries to keep these out of the way unless we're actively playing a replay
- Now handles detecting pointer over objects correctly based on our overrides
- Fixes an issue where 2D mouse over object hits weren't being detected properly
- This PR DOES NOT make the Match3 fully work with recording / replay... there are many more unique-ness-es about the game that require using behaviour segments instead of recording.
---
> [REG-1950] Better manage event system lifecycle + fix legacy 2D mouse clicks

- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGDraggedCard.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGDropZone.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceEntry.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceManager.cs
- Fixes null sequencemanager issue in Match3
- Fixes some misuses of ?. on gameObjects
---
> [REG-2058] [REG-2062] Fix null sequenceManager and some misuse of ?. on gameobjects

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
> [REG-2066] Fix brace issue

- src/gg.regression.unity.bots/Runtime/Images/CardLeft.png
- src/gg.regression.unity.bots/Runtime/Images/CardLeft.png.meta
- src/gg.regression.unity.bots/Runtime/Images/CardRight.png
- src/gg.regression.unity.bots/Runtime/Images/CardRight.png.meta
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/SegmentCardLarge.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/SegmentCardLarge.prefab.meta
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/Sequence Editor.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlay/Tooltip.prefab
- src/gg.regression.unity.bots/Runtime/Prefabs/RGOverlayCanvas.prefab
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSegmentEntry.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSegmentEntry.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceEditor.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGTabButton.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGTabButton.cs.meta
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequence.cs
- src/gg.regression.unity.bots/Tests/Scripts/RGOverlay/RGSegmentEntry.test.cs
- src/gg.regression.unity.bots/Tests/Scripts/RGOverlay/RGSegmentEntry.test.cs.meta
- src/gg.regression.unity.bots/Tests/Scripts/RGOverlay/RGSequenceManager.test.cs
https://github.com/user-attachments/assets/8c1111a6-8fa8-4aff-a400-356b7f070da8
- Users can view a list of Segments and play individual ones
- Users can switch tabs between the list of Sequences and the list of Segments
- Better Tooltip anchor positioning
- Created a `SegmentCardLarge` that is similar to the `SequenceCard`. This provides a view of a Segment that is better suited for interaction and displaying more content than the existing `SegmentCard`  (as seen in the Sequence Editor)
- Additional testing
https://www.loom.com/share/e53230f066a547de8e5d514927d5b236
> [REG-1951] Segments List + Play Segment in the SDK UI

- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/ScreenRecorder.cs
- Excludes copying recordings of replays into the project as the 'latest recording'
---
> [REG-2070] Don't copy recordings of the replay into the project

- src/RGUnityBots/Assets/RegressionGames/Resources/BotSegments.meta
- src/RGUnityBots/Assets/RegressionGames/Resources/RGBotSequences.asset
- src/gg.regression.unity.bots/Runtime/Scripts/RGServiceManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RemoteOrchestration/Models/WorkAssignment.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RemoteOrchestration/RGRemoteWorkerAssignmentManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RemoteOrchestration/Types/SDKClientHeartbeatRequest.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RemoteOrchestration/Types/SDKClientHeartbeatResponse.cs
- src/gg.regression.unity.bots/Runtime/Scripts/RemoteOrchestration/Types/SDKClientRegistrationRequest.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequence.cs
- Fixes payload snafus around nullables, especially around receiving
- Fixes broken timeout logic to use the actual start time it started on this machine so runs don't timeout instantly due to network latency and short timeout values
- Fixes a bug where SDK was sending incorrect heartbeat status
- Changes how we send the json for these payloads to be more efficient per @addisonbgross suggestion
- Fixes an OBOB in the ip address iterators
---
> [REG-2139] Correct SDK <-> API communication and coordination issues

- src/gg.regression.unity.bots/Runtime/Scripts/RGOverlay/RGSequenceManager.cs
- src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSequence.cs
Small improvement to an error message to reduce user error. 
For internal RG team members, see this thread for context: https://regressiongames.slack.com/archives/C0820NEU8DA/p1732295615249689
> [IF] Small improvement to an error message
